services:
  # localhost:32400/web
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - VERSION=docker
    volumes:
      - /mnt/Seagate/plex-config:/config
      - /mnt/Seagate/data/media:/data/media
      - /dev/shm:/transcode
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  # localhost:8080
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/Seagate/sabnzbd-config:/config
      - /mnt/Seagate/data/sabnzbd:/data/sabnzbd
    ports:
      - 8080:8080
    restart: unless-stopped

