services:
  # localhost:32400/web
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - VERSION=docker
    volumes:
      - /mnt/Seagate/plex_config:/config
      - /mnt/Seagate/data/media:/data/media
      - /dev/shm:/transcode
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

