#!/bin/bash

if [ -z "$1" ]; then
  echo "need source and destination paths"
  exit 1
fi

if [[ -n "$1" && -z "$2" ]]; then
  echo "need destination path"
  exit 1
fi

export GOGC=10

sudo rclone copy --update --fast-list --verbose --transfers 3 --checkers 3 --tpslimit 3 --max-backlog 200000 --contimeout 60s --timeout 300s --retries 3 --low-level-retries 10 --stats 10s "$1" "$2"
