#!/usr/bin/python3

import os
import json
import time

# run ngrok with ssh tunnel
os.system("nohup ngrok start ssh > /dev/null &")
time.sleep(1)

# use ngrok api to get ngrok dashboard data
stream = os.popen("curl -s http://localhost:4040/api/tunnels/ssh")
output = stream.read()
ngrokData = json.loads(output)
public_url = ngrokData["public_url"]

print("public_url: {}".format(public_url))

# post txt file on ix.io w/ public_url
os.system("echo {} > current_public_url && ix current_public_url && rm current_public_url".format(public_url))
