notARepository: skip
promptToReturnFromSubprocess: false
os:
  editPreset: 'nvim-remote'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
gui:
  skipDiscardChangeWarning: true
  nerdFontsVersion: "3"
  showFileTree: false
  showCommandLog: false
  showBottomLine: true
  theme:
    selectedLineBgColor:
      - black
customCommands:
  - key: 'C'
    context: 'files'
    command: 'aicommits'
    subprocess: true
    stream: true
