notARepository: skip
promptToReturnFromSubprocess: false
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
gui:
  nerdFontsVersion: "3"
  showFileTree: true
  showCommandLog: false
  showBottomLine: true
  theme:
    selectedLineBgColor:
      - black
customCommands:
  - key: 'C'
    context: 'files'
    command: 'aicommits'
    subprocess: true
    stream: true
