# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

notARepository: skip
promptToReturnFromSubprocess: false
os:
  editPreset: "nvim-remote"
  # editPreset: "nvim"
  # edit: '[ -z "$NVIM" ] && nvim -- {{filename}} || (nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote-tab {{filename}})'
  # editAtLine: '[ -z "$NVIM" ] && (nvim +{{line}} -- {{filename}}) || (nvim --server "$NVIM" --remote-send "q" &&  nvim --server "$NVIM" --remote {{filename}} && nvim --server "$NVIM" --remote-send ":{{line}}<CR>")'
  # editAtLineAndWait: "nvim +{{line}} {{filename}}"
  # openDirInEditor: '[ -z "$NVIM" ] && (nvim -- {{dir}}) || (nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote {{dir}})'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
gui:
  skipDiscardChangeWarning: true
  nerdFontsVersion: "3"
  showFileTree: true
  showCommandLog: false
  showBottomLine: true
  theme:
    selectedLineBgColor:
      - blue
customCommands:
  - key: "C"
    context: "files"
    command: "aicommits"
    output: terminal
  - key: "Y"
    description: "Open Yazi at hovered file"
    context: "files"
    command: "yazi {{.SelectedFile.Name}}"
    output: terminal
  - key: "Y"
    description: "Open Yazi at hovered file"
    context: "commitFiles"
    command: "yazi {{.SelectedCommitFile.Name}}"
    output: terminal
