# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

notARepository: skip
promptToReturnFromSubprocess: false
os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim +{{line}} {{filename}}"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
gui:
  skipDiscardChangeWarning: true
  nerdFontsVersion: "3"
  showFileTree: true
  showCommandLog: false
  showBottomLine: true
  theme:
    selectedLineBgColor:
      - "#323847"
customCommands:
  - key: "C"
    context: "files"
    command: "aicommits"
    output: terminal
  - key: "Y"
    description: "Open Yazi at hovered file"
    context: "files"
    command: "yazi {{.SelectedFile.Name}}"
    output: terminal
  - key: "Y"
    description: "Open Yazi at hovered file"
    context: "commitFiles"
    command: "yazi {{.SelectedCommitFile.Name}}"
    output: terminal
