#!/usr/bin/env bash

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <destination> <ultx-service>"
  echo "Example: $0 65 agents"
  exit 1
fi

dst_num="$1"
shift
services=("$@")

commands=()
for service in "${services[@]}"; do
  commands+=("ultx restart $service &&")
done
[[ ${#services[@]} -eq 0 ]] && commands+=("ultx restart all &&")

ssh "$dst_num" "${commands[*]} ntfy 20"
