services:
  # localhost:5055
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    env_file: .env
    environment:
      - LOG_LEVEL=debug
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - $HOME/.media_server/jellyseerr-config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
  # localhost:8096
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    env_file: .env
    environment:
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    #   - JELLYFIN_PublishedServerUrl=http://192.168.0.5
    volumes:
      - $HOME/.media_server/jellyfin-config:/config
      - /mnt/Seagate/data/media/tv:/data/tv
      - /mnt/Seagate/data/media/movies:/data/movies
    ports:
      - 8096:8096 # http webUI
      - 7359:7359/udp # Allows clients to discover Jellyfin on the local network
      - 1900:1900/udp # Service discovery used by DNLA and clients
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  # localhost:8080
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    env_file: .env
    volumes:
      - $HOME/.media_server/sabnzbd-config:/config
      - $HOME/downloads/sabnzbd:/data/sabnzbd
    ports:
      - 8080:8080
    restart: unless-stopped

  # localhost:7878
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file: .env
    volumes:
      - $HOME/.media_server/radarr-config:/config
      - /mnt/Seagate/data/media:/data/media
      - $HOME/downloads/sabnzbd:/data/sabnzbd
    ports:
      - 7878:7878
    restart: unless-stopped

  # localhost:8989
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file: .env
    volumes:
      - $HOME/.media_server/sonarr-config:/config
      - /mnt/Seagate/data/media:/data/media
      - $HOME/downloads/sabnzbd:/data/sabnzbd
    ports:
      - 8989:8989
    restart: unless-stopped
