services:
  # localhost:8096
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    env_file: .env
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://192.168.0.5
    volumes:
      - /mnt/Seagate/jellyfin-config:/config
      - /mnt/Seagate/data/media/tv:/data/tv
      - /mnt/Seagate/data/media/movies:/data/movies
    ports:
      - 8096:8096 # http webUI
      - 7359:7359/udp # Allows clients to discover Jellyfin on the local network
      - 1900:1900/udp # Service discovery used by DNLA and clients
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  # localhost:8080
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    env_file: .env
    volumes:
      - /mnt/Seagate/sabnzbd-config:/config
      - /home/bnew10/downloads/sabnzbd:/data/sabnzbd
    ports:
      - 8080:8080
    restart: unless-stopped

  # localhost:7878
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file: .env
    volumes:
      - /mnt/Seagate/radarr-config:/config
      - /mnt/Seagate/data/media:/data/media
      - /home/bnew10/downloads/sabnzbd:/data/sabnzbd
    ports:
      - 7878:7878
    restart: unless-stopped

  # localhost:8989
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file: .env
    volumes:
      - /mnt/Seagate/sonarr-config:/config
      - /mnt/Seagate/data/media:/data/media
      - /home/bnew10/downloads/sabnzbd:/data/sabnzbd
    ports:
      - 8989:8989
    restart: unless-stopped

  # localhost:5055
  # overseerr:
  #   image: sctx/overseerr:latest
  #   container_name: overseerr
  #   env_file: .env
  #   volumes:
  #     - /mnt/Seagate/overseerr-config:/app/config
  #   ports:
  #     - 5055:5055
  #   restart: unless-stopped
