#!/usr/bin/env bash

## aliases
alias lal="ls -Alh --color=auto"
alias c="clear && cd"
path() {
  echo "${PATH//:/\n}"
}

## jar debug string (jds)
DEBUG_STR='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005'
alias jds="tee >(tr -d '\n' | pbcopy) <<< $DEBUG_STR"

## maven format
alias mf='mvn com.coveo:fmt-maven-plugin:format'

## homebrew
# alias bud="brew update && echo '\n' && brew outdated --greedy"
bud() {
  brew update

  local json
  json=$(brew outdated --greedy --json)
  local formulae
  formulae=$(echo "$json" | jq -r '.formulae[] | .name + "|" + (.installed_versions | join(", ")) + "|" + .current_version')
  local casks
  casks=$(echo "$json" | jq -r '.casks[] | .name + "|" + (.installed_versions | join(", ")) + "|" + .current_version')
  local output
  output=''

  if [[ -n $formulae ]]; then
    output+='\n\e[4mFormulae\e[24m\n'
    while IFS=$'\n' read -r formula; do
      IFS='|' read -r name installed_versions current_version <<<"$formula"
      output+="$name ($installed_versions) < $current_version\n"
    done <<<"$formulae"
  fi

  if [[ -n $casks ]]; then
    output+='\n\e[4mCasks\e[24m\n'
    while IFS=$'\n' read -r cask; do
      IFS='|' read -r name installed_versions current_version <<<"$cask"
      output+="$name ($installed_versions) < $current_version\n"
    done <<<"$casks"
  fi

  echo -n "$output"
}
alias bug="brew upgrade --greedy"
alias bugf="brew upgrade --formula"
alias bugc="brew upgrade --cask --greedy"

## github copilot cli
alias ghcs="gh copilot suggest"
alias ghce="gh copilot explain"

## tms
alias tms-sessions-red="tms sessions | sed -E 's/([[:alnum:]]+)\*/\x1b[31m\1\x1b[0m/g'"

## git
unalias gcp &>/dev/null
# for copying newline separated lists into clipboard as space separated lists
# ex: `git diff --name-only | gcp`
gcp() {
  tee >(tr '\n' ' ' | pbcopy)
}

alias gsh='git show --first-parent'

# copy file paths of listed files in git show
gshc() {
  git show --first-parent --name-only --pretty=format: "$@" | gcp
}

# checkout files from given MRs into current branch
# args: <from_branch> <gitlab MR ref 1> <gitlab MR ref 2> ...
gcmf() {
  local from="$1"
  shift

  readarray -t commit_args < <(git log --format='%h' "${@/*/--grep=&}" "$from")

  readarray -t path_args < <(git show --first-parent --name-only --pretty=format: "${commit_args[@]}" | sort -u | sed '/^[[:space:]]*$/d')

  git checkout "$from" "${path_args[@]}"
}

alias gst='git-st'

# get relative paths of given file paths
git-reltocwd() {
  xargs -I {} grealpath -s --relative-to='.' "$(git rev-parse --show-toplevel)/{}"
}

# get path of current dir from git root (e.g., 'scripts-tools/nnn/')
git-path() {
  printf "%s/%s" "$(basename $(git rev-parse --show-toplevel))" "$(git rev-parse --show-prefix)"
}

jars() {
  git status --porcelain | awk -F '/' '{ print $2 }' | uniq
}

alias gt='cd "$(git rev-parse --show-toplevel)"'

alias gco='git checkout'
alias gcb='git checkout -b'
alias gd='git diff'

## raycast
alias confetti="open -g raycast://confetti"
alias raycast="open /Applications/Raycast.app"

## docker
# enter container's shell
dsh() {
  docker exec -it "$1" /bin/bash
}

export COMPOSE_DIR=("$HOME/scripts-tools/media-server/compose.yml")
# update containers in compose file
dcupdate() {
  docker compose -f "${COMPOSE_DIR[@]}" pull "$1" && docker compose -f "${COMPOSE_DIR[@]}" up -d "$1"
}

alias dc='docker compose'

## ultx
is-active() {
  ultx is-active | awk '{if ($0 ~ /active/) {print "\033[0;32m" $0 "\033[0m"} else if ($0 ~ /failed/) {print "\033[0;31m" $0 "\033[0m"} else {print $0}}'
}

ug() {
  local tarball
  if [[ "$1" =~ ^http ]]; then
    wget "$1" || return $?
    tarball="$(awk -F '/' '{print $NF}' <<<"$1")"
  else
    tarball="$1"
  fi

  /usr/share/vcinity/configuration/bin/ultx_upgrade.sh -d "$tarball"
}

## lazygit
gl() {
  export LAZYGIT_NEW_DIR_FILE=~/.lazygit/newdir

  lazygit "$@"

  if [ -f $LAZYGIT_NEW_DIR_FILE ]; then
    cd "$(cat $LAZYGIT_NEW_DIR_FILE)"
    rm -f $LAZYGIT_NEW_DIR_FILE >/dev/null
  fi
}

## man
man() {
  if [[ -n $TMUX ]]; then
    local man_path
    man_path=$(command man -w "$@")
    local pane_id
    pane_id=$(tmux display -p '#{s/%%//:pane_id}')
    tmux set-environment "CURRENT_MAN_${pane_id}" "$man_path"

    local win_id
    win_id="$(tmux display -p '#{window_id}')"

    tmux rename-window -t ":$win_id" "man $*"
    command man "$@"
    tmux set-option -wt ":$win_id" automatic-rename on

    tmux set-environment -u "CURRENT_MAN_${pane_id}"
  else
    command man "$@"
  fi
}

## yazi
y() {
  local tmp
  tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
  yazi "$@" --cwd-file="$tmp"
  if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
    # shellcheck disable=SC2164
    builtin cd -- "$cwd"
  fi
  rm -f -- "$tmp"
}

### misc
# sends macos notification when run
completed() {
  if [[ -n $TMUX || $TMUX_ESC ]]; then
    printf "\033Ptmux;\033\033]9;Completed\007\033\\"
  else
    printf "\033]9;Completed\007"
  fi
}

alias as='atuin scripts'
alias asr='atuin scripts run'

# delta-diff
[[ -f "$HOME/scripts-tools/bin/delta-diff" ]] && source "$HOME/scripts-tools/bin/delta-diff"
