#!/usr/bin/env zsh

# manually source ghostty shell integration to bring it into all shells
if [[ -n $GHOSTTY_RESOURCES_DIR ]]; then
  source "$GHOSTTY_RESOURCES_DIR"/shell-integration/zsh/ghostty-integration
fi

brew_paths=(
  "/opt/homebrew/bin/brew"
  "/home/linuxbrew/.linuxbrew/bin/brew"
)
for brew_path in "${brew_paths[@]}"; do
  if command -v "$brew_path" >/dev/null; then
    brew_cmd="$brew_path"
    break
  fi
done

if [[ -n $brew_cmd ]]; then
  # set important homebrew params like $HOMEBREW_PREFIX
  eval "$($brew_cmd shellenv)"
  autoload -Uz compinit
  compinit
fi

source_files=(
  ".aliases"
  ".env"
  ".java_env"
  ".api_keys"
)
for src in "${source_files[@]}"; do
  src_path="$HOME/$src"
  [[ -e $src_path ]] && source "$src_path"
done

# zsh-autosuggestions
if [[ -n $HOMEBREW_PREFIX ]]; then
  source "$HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
fi

# Options
setopt CORRECT
setopt CORRECT_ALL

eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
