services:
  # localhost:32400/web
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - VERSION=docker
    volumes:
      - /mnt/Seagate/plex-config:/config
      - /mnt/Seagate/data/media:/data/media
      - /dev/shm:/transcode
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  # localhost:8080
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/Seagate/sabnzbd-config:/config
      - /home/bnew10/downloads/sabnzbd:/data/sabnzbd
    ports:
      - 8080:8080
    restart: unless-stopped

  # localhost:7878
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/Seagate/radarr-config:/config
      - /mnt/Seagate/data/media:/data/media
      - /home/bnew10/downloads/sabnzbd:/data/sabnzbd
    ports:
      - 7878:7878
    restart: unless-stopped

  # localhost:8989
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/Seagate/sonarr-config:/config
      - /mnt/Seagate/data/media:/data/media
      - /home/bnew10/downloads/sabnzbd:/data/sabnzbd
    ports:
      - 8989:8989
    restart: unless-stopped

